  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Educated ramblings"
  weight = 210
  identifier = "educated_ramblings"
  url = "/educated_ramblings/"
  parent = "posts"

  [[main]]
  name = "Journal Reviews"
  weight = 220
  identifier = "journal_reviews"
  url = "/journal_reviews/"
  parent = "posts"





  [[main]]
  name = "Contact"
  weight = 300
  identifier = "contact"
  url = "/contact/"

